spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:~/test1;
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        show_sql: true
    hibernate:
      ddl-auto: create-drop
  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: xVxEzrXhcVGfJpZzzR_x
            redirect-uri: http://localhost:8080/login/oauth/code/naver
            authorization-grant-type: authorization_code
            client-secret: uv72h_O_VH
          kakao:
            client-secret: HK2RSKDHJHcwkb6jFW6yVIIbhEogX7mN
            redirect-uri: http://localhost:8080/login/oauth/code/kakao
            authorization-grant-type: authorization_code
            client-id: d9b6ea43550fd5a1d8b8a6487b0a4aee
            client-authentication-method: POST
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
            token-uri: https://nid.naver.com/oauth2.0/token
          kakao:
            user-name-attribute: kakao_account
            user-info-uri: https://kapi.kakao.com/v2/user/me
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
email:
  address:
    admin: admin@gmail.com
jwt:
  key: codedkowksmdlalskdkfkdksdkoekskdkmvzls3dksz2sld
  access-token-expiration-minutes: 300
  refresh-token-expiration-minutes: 600